import type { FertilizerRecommendation } from "./types"

export const FERTILIZER_DATABASE: Record<string, Omit<FertilizerRecommendation, "id" | "score">[]> = {
  sugarcane: [
    {
      name: "Urea (46-0-0)",
      npkRatio: "46-0-0",
      nitrogen: 46,
      phosphorus: 0,
      potassium: 0,
      dosage: "200-250 kg/acre",
      applicationMethod: "Split application: 50% at planting, 25% at 45 days, 25% at 90 days",
      benefits: [
        "High nitrogen content for vegetative growth",
        "Cost-effective nitrogen source",
        "Quick release for rapid growth",
        "Improves leaf development",
      ],
    },
    {
      name: "DAP (18-46-0)",
      npkRatio: "18-46-0",
      nitrogen: 18,
      phosphorus: 46,
      potassium: 0,
      dosage: "100-150 kg/acre",
      applicationMethod: "Apply at planting time, incorporate into soil",
      benefits: [
        "Excellent phosphorus source",
        "Promotes root development",
        "Enhances early growth",
        "Improves tillering",
      ],
    },
    {
      name: "MOP (0-0-60)",
      npkRatio: "0-0-60",
      nitrogen: 0,
      phosphorus: 0,
      potassium: 60,
      dosage: "80-120 kg/acre",
      applicationMethod: "Split application: 50% at planting, 50% at 60 days",
      benefits: [
        "High potassium content",
        "Improves sugar content",
        "Enhances disease resistance",
        "Better drought tolerance",
      ],
    },
    {
      name: "NPK 12-32-16",
      npkRatio: "12-32-16",
      nitrogen: 12,
      phosphorus: 32,
      potassium: 16,
      dosage: "150-200 kg/acre",
      applicationMethod: "Apply at planting, band placement near seed",
      benefits: [
        "Balanced nutrition",
        "Good starter fertilizer",
        "Promotes overall growth",
        "Suitable for all soil types",
      ],
    },
    {
      name: "Potassium Nitrate (13-0-46)",
      npkRatio: "13-0-46",
      nitrogen: 13,
      phosphorus: 0,
      potassium: 46,
      dosage: "100-150 kg/acre",
      applicationMethod: "Apply during flowering and fruit development",
      benefits: [
        "High potassium for sugar quality",
        "Improves fruit size and quality",
        "Reduces disease susceptibility",
        "Better shelf life",
      ],
    },
  ],
  rice: [
    {
      name: "Urea (46-0-0)",
      npkRatio: "46-0-0",
      nitrogen: 46,
      phosphorus: 0,
      potassium: 0,
      dosage: "120-150 kg/acre",
      applicationMethod: "Split: 50% at planting, 25% at tillering, 25% at panicle initiation",
      benefits: [
        "Essential for rice grain development",
        "Improves yield and grain quality",
        "Cost-effective nitrogen source",
        "Quick absorption by plants",
      ],
    },
    {
      name: "DAP (18-46-0)",
      npkRatio: "18-46-0",
      nitrogen: 18,
      phosphorus: 46,
      potassium: 0,
      dosage: "80-100 kg/acre",
      applicationMethod: "Apply at planting time as basal dose",
      benefits: [
        "Promotes strong root system",
        "Enhances early vigor",
        "Improves tillering in rice",
        "Better nutrient uptake",
      ],
    },
    {
      name: "MOP (0-0-60)",
      npkRatio: "0-0-60",
      nitrogen: 0,
      phosphorus: 0,
      potassium: 60,
      dosage: "40-60 kg/acre",
      applicationMethod: "Apply at panicle initiation stage",
      benefits: [
        "Improves grain filling",
        "Enhances disease resistance",
        "Better straw quality",
        "Increases 1000-grain weight",
      ],
    },
    {
      name: "NPK 20-20-20",
      npkRatio: "20-20-20",
      nitrogen: 20,
      phosphorus: 20,
      potassium: 20,
      dosage: "100-120 kg/acre",
      applicationMethod: "Split application at tillering and panicle initiation",
      benefits: [
        "Complete balanced nutrition",
        "Suitable for all soil types",
        "Improves overall yield",
        "Easy to apply and manage",
      ],
    },
    {
      name: "Ammonium Sulfate (21-0-0)",
      npkRatio: "21-0-0",
      nitrogen: 21,
      phosphorus: 0,
      potassium: 0,
      dosage: "100-130 kg/acre",
      applicationMethod: "Apply in split doses during growing season",
      benefits: [
        "Provides nitrogen and sulfur",
        "Improves protein content in grain",
        "Acidifies alkaline soils",
        "Long-lasting nitrogen effect",
      ],
    },
  ],
  wheat: [
    {
      name: "Urea (46-0-0)",
      npkRatio: "46-0-0",
      nitrogen: 46,
      phosphorus: 0,
      potassium: 0,
      dosage: "100-120 kg/acre",
      applicationMethod: "Split: 50% at sowing, 50% at tillering stage",
      benefits: [
        "Critical for grain protein content",
        "Improves yield potential",
        "Cost-effective nitrogen source",
        "Quick availability to plants",
      ],
    },
    {
      name: "DAP (18-46-0)",
      npkRatio: "18-46-0",
      nitrogen: 18,
      phosphorus: 46,
      potassium: 0,
      dosage: "80-100 kg/acre",
      applicationMethod: "Apply at sowing time as basal fertilizer",
      benefits: [
        "Promotes root development",
        "Enhances early growth vigor",
        "Improves nutrient availability",
        "Better establishment of crop",
      ],
    },
    {
      name: "MOP (0-0-60)",
      npkRatio: "0-0-60",
      nitrogen: 0,
      phosphorus: 0,
      potassium: 60,
      dosage: "40-50 kg/acre",
      applicationMethod: "Apply at tillering or boot stage",
      benefits: [
        "Improves grain quality",
        "Enhances disease resistance",
        "Better straw strength",
        "Increases test weight",
      ],
    },
    {
      name: "NPK 15-15-15",
      npkRatio: "15-15-15",
      nitrogen: 15,
      phosphorus: 15,
      potassium: 15,
      dosage: "100-120 kg/acre",
      applicationMethod: "Apply at sowing and top-dress at tillering",
      benefits: [
        "Balanced nutrition for all stages",
        "Suitable for all soil types",
        "Improves overall productivity",
        "Easy to manage and apply",
      ],
    },
    {
      name: "Calcium Ammonium Nitrate (26-0-0)",
      npkRatio: "26-0-0",
      nitrogen: 26,
      phosphorus: 0,
      potassium: 0,
      dosage: "80-100 kg/acre",
      applicationMethod: "Split application during growing season",
      benefits: [
        "Nitrogen with calcium for strong stems",
        "Prevents lodging in wheat",
        "Improves grain quality",
        "Better disease resistance",
      ],
    },
  ],
  corn: [
    {
      name: "Urea (46-0-0)",
      npkRatio: "46-0-0",
      nitrogen: 46,
      phosphorus: 0,
      potassium: 0,
      dosage: "150-180 kg/acre",
      applicationMethod: "Split: 50% at planting, 50% at V6-V8 stage",
      benefits: [
        "Essential for corn grain development",
        "Improves yield significantly",
        "Cost-effective nitrogen source",
        "Quick plant uptake",
      ],
    },
    {
      name: "DAP (18-46-0)",
      npkRatio: "18-46-0",
      nitrogen: 18,
      phosphorus: 46,
      potassium: 0,
      dosage: "100-120 kg/acre",
      applicationMethod: "Apply at planting time",
      benefits: [
        "Promotes strong root system",
        "Enhances early vigor",
        "Improves nutrient uptake",
        "Better plant establishment",
      ],
    },
    {
      name: "MOP (0-0-60)",
      npkRatio: "0-0-60",
      nitrogen: 0,
      phosphorus: 0,
      potassium: 60,
      dosage: "60-80 kg/acre",
      applicationMethod: "Apply at V4-V6 stage",
      benefits: [
        "Improves grain filling",
        "Enhances disease resistance",
        "Better stalk strength",
        "Increases kernel weight",
      ],
    },
    {
      name: "NPK 10-26-26",
      npkRatio: "10-26-26",
      nitrogen: 10,
      phosphorus: 26,
      potassium: 26,
      dosage: "120-150 kg/acre",
      applicationMethod: "Apply at planting for balanced nutrition",
      benefits: [
        "Balanced P and K for development",
        "Improves grain quality",
        "Enhances disease resistance",
        "Suitable for maintenance feeding",
      ],
    },
    {
      name: "Diammonium Phosphate (21-53-0)",
      npkRatio: "21-53-0",
      nitrogen: 21,
      phosphorus: 53,
      potassium: 0,
      dosage: "80-100 kg/acre",
      applicationMethod: "Apply at planting, incorporate well",
      benefits: [
        "High phosphorus for root development",
        "Nitrogen for early growth",
        "Improves nutrient availability",
        "Good for deficient soils",
      ],
    },
  ],
  cotton: [
    {
      name: "Urea (46-0-0)",
      npkRatio: "46-0-0",
      nitrogen: 46,
      phosphorus: 0,
      potassium: 0,
      dosage: "120-150 kg/acre",
      applicationMethod: "Split: 50% at planting, 50% at flowering",
      benefits: [
        "Essential for cotton fiber development",
        "Improves yield and quality",
        "Cost-effective nitrogen source",
        "Promotes vegetative growth",
      ],
    },
    {
      name: "DAP (18-46-0)",
      npkRatio: "18-46-0",
      nitrogen: 18,
      phosphorus: 46,
      potassium: 0,
      dosage: "80-100 kg/acre",
      applicationMethod: "Apply at planting time",
      benefits: [
        "Promotes root development",
        "Enhances early vigor",
        "Improves nutrient uptake",
        "Better plant establishment",
      ],
    },
    {
      name: "MOP (0-0-60)",
      npkRatio: "0-0-60",
      nitrogen: 0,
      phosphorus: 0,
      potassium: 60,
      dosage: "80-100 kg/acre",
      applicationMethod: "Split: 50% at planting, 50% at flowering",
      benefits: [
        "Improves fiber quality and strength",
        "Enhances disease resistance",
        "Better boll development",
        "Increases lint percentage",
      ],
    },
    {
      name: "NPK 12-32-16",
      npkRatio: "12-32-16",
      nitrogen: 12,
      phosphorus: 32,
      potassium: 16,
      dosage: "120-150 kg/acre",
      applicationMethod: "Apply at planting for balanced nutrition",
      benefits: [
        "Balanced nutrition for all stages",
        "Good starter fertilizer",
        "Promotes overall growth",
        "Suitable for all soil types",
      ],
    },
    {
      name: "Potassium Nitrate (13-0-46)",
      npkRatio: "13-0-46",
      nitrogen: 13,
      phosphorus: 0,
      potassium: 46,
      dosage: "100-120 kg/acre",
      applicationMethod: "Apply during flowering and boll development",
      benefits: [
        "High potassium for fiber quality",
        "Improves boll size and weight",
        "Reduces disease susceptibility",
        "Better lint quality",
      ],
    },
  ],
  vegetables: [
    {
      name: "NPK 20-20-20",
      npkRatio: "20-20-20",
      nitrogen: 20,
      phosphorus: 20,
      potassium: 20,
      dosage: "80-120 kg/acre",
      applicationMethod: "Split application throughout growing season",
      benefits: [
        "Complete balanced nutrition",
        "Suitable for all vegetable types",
        "Promotes healthy growth",
        "Improves yield and quality",
      ],
    },
    {
      name: "DAP (18-46-0)",
      npkRatio: "18-46-0",
      nitrogen: 18,
      phosphorus: 46,
      potassium: 0,
      dosage: "60-80 kg/acre",
      applicationMethod: "Apply at planting time",
      benefits: [
        "Promotes root development",
        "Enhances early vigor",
        "Improves nutrient uptake",
        "Better plant establishment",
      ],
    },
    {
      name: "Urea (46-0-0)",
      npkRatio: "46-0-0",
      nitrogen: 46,
      phosphorus: 0,
      potassium: 0,
      dosage: "60-100 kg/acre",
      applicationMethod: "Split application during growing season",
      benefits: [
        "Promotes leafy growth",
        "Improves vegetable quality",
        "Cost-effective nitrogen source",
        "Quick plant response",
      ],
    },
    {
      name: "MOP (0-0-60)",
      npkRatio: "0-0-60",
      nitrogen: 0,
      phosphorus: 0,
      potassium: 60,
      dosage: "40-60 kg/acre",
      applicationMethod: "Apply during fruit/pod development",
      benefits: [
        "Improves fruit quality and taste",
        "Enhances disease resistance",
        "Better shelf life",
        "Increases yield",
      ],
    },
    {
      name: "Ammonium Sulfate (21-0-0)",
      npkRatio: "21-0-0",
      nitrogen: 21,
      phosphorus: 0,
      potassium: 0,
      dosage: "80-120 kg/acre",
      applicationMethod: "Apply in split doses during growing season",
      benefits: [
        "Provides nitrogen and sulfur",
        "Improves vegetable quality",
        "Acidifies alkaline soils",
        "Long-lasting nitrogen effect",
      ],
    },
  ],
}
